acme_store_homepage:
    pattern:  /hellos/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }

acme_store_create:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:create }

acme_store_update:
    pattern:  /update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update }

acme_store_productos:
    pattern:  /productos
    defaults: { _controller: AcmeStoreBundle:Default:productos }

acme_store_show:
    pattern:  /show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show }